# Generated by Django 5.1.15 on 2026-03-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evidence",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="evidence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("PROCESSING", "Processing"),
                    ("EXTRACTED", "Extracted"),
                    ("ANALYZING", "Analyzing"),
                    ("ANALYZED", "Analyzed"),
                    ("FAILED", "Failed"),
                ],
                default="UPLOADED",
                max_length=20,
            ),
        ),
    ]
