# Generated by Django 5.1.15 on 2026-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0002_evidence_error_message_evidence_file_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("EXTRACTING", "Extracting"),
                    ("PROCESSING", "Processing"),
                    ("EXTRACTED", "Extracted"),
                    ("ANALYZING", "Analyzing"),
                    ("ANALYZED", "Analyzed"),
                    ("FAILED", "Failed"),
                ],
                default="UPLOADED",
                max_length=20,
            ),
        ),
    ]
