# Generated by Django 5.1.15 on 2026-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_sprint1_membership_invitation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invitation",
            new_name="organizatio_email_dfac8a_idx",
            old_name="invite_org_email",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="organizatio_token_a43b03_idx",
            old_name="invite_token",
        ),
        migrations.AlterField(
            model_name="organization",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
