# Generated by Django 5.1.15 on 2026-03-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organizationinvite",
            new_name="accounts_or_email_7baab3_idx",
            old_name="accounts_organizationinvite_email_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationinvite",
            new_name="accounts_or_token_985f01_idx",
            old_name="accounts_organizationinvite_token_idx",
        ),
    ]
