# Generated by Django 5.1.15 on 2026-03-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=120)),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("PARTIAL", "Partial"),
                            ("NON_COMPLIANT", "Non Compliant"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("confidence", models.PositiveIntegerField(default=0)),
                ("missing_points", models.JSONField(blank=True, null=True)),
                ("recommendations", models.JSONField(blank=True, null=True)),
                ("citations", models.JSONField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                ("summary_ar", models.TextField(blank=True, null=True)),
                ("summary_en", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
