# Generated by Django 5.1.15 on 2026-03-05 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_engine", "0001_initial"),
        ("controls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysisresult",
            name="control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_results",
                to="controls.control",
            ),
        ),
    ]
