# Generated by Django 5.1.15 on 2026-03-05 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_engine", "0002_initial"),
        ("evidence", "0001_initial"),
        (
            "organizations",
            "0003_rename_invite_org_email_organizatio_email_dfac8a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysisresult",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_results",
                to="evidence.evidence",
            ),
        ),
        migrations.AddField(
            model_name="aianalysisresult",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_results",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["organization", "control", "created_at"],
                name="ai_engine_a_organiz_07375a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["evidence", "control"], name="ai_engine_a_evidenc_83c98c_idx"
            ),
        ),
    ]
