# Generated by Django 5.1.15 on 2026-03-05 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0003_rename_invite_org_email_organizatio_email_dfac8a_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("title_ar", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("description_ar", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("required_evidence", models.TextField(blank=True, default="")),
                ("references", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="controls.controlcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ControlScoreSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("PARTIAL", "Partial"),
                            ("NON_COMPLIANT", "Non Compliant"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_snapshots",
                        to="controls.control",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_scores",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "control", "computed_at"],
                        name="controls_co_organiz_3ceccb_idx",
                    )
                ],
            },
        ),
    ]
